# trigger:
# - main

variables:
  projectPath: my-react-app

stages:
  - stage: build_artifact
    displayName: Build artifact
    jobs:
      - job: Build
        pool: 
          vmImage: windows-latest
        steps:
          - task: UseNode@1
            displayName: Install node.js
            inputs:
              checkLatest: true

          - task: Npm@1
            inputs:
              command: 'install'
              workingDir: my-react-app

          - task: Npm@1
            inputs:
              command: 'run build'
              workingDir: my-react-app

          # - script: |
          #     echo 'Change directory...'
          #     cd my-react-app
          #     echo 'Build project...'
          #     npm 
          #     echo 'Current directory...'
          #     pwd
          #     ls
          #   displayName: Npm install and build

              # echo 'NPM Install...'
              # npm install -verbose
          # - task: PublishBuildArtifacts@1
          #   displayName: Publish artifact
          #   inputs:
          #     PathtoPublish: 'my-react-app/build'
          #     ArtifactName: 'build-output'