trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  displayName: Install node.js
  inputs:
    versionSource: 'spec'
    versionSpec: '18.x'
    checkLatest: true

- script: |
    npm install
    npm run build
  displayName: npm install and build
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'build-output'