# trigger:
# - main

variables:
  projectPath: my-react-app

stages:
  - stage: build_artifact
    displayName: Build artifact
    jobs:
      - job: Build
        pool: 
          vmImage: windows-latest
        steps:
          - task: UseNode@1
            displayName: Install node.js
            inputs:
              checkLatest: true

          - script: |
              echo 'Change directory...'
              cd my-react-app
              echo 'NPM Install...'
              npm install -f
              echo 'Build project...'
              npm run build
              echo 'Current directory...'
              pwd
              ls
            displayName: Npm install and build
  
          # - task: PublishBuildArtifacts@1
          #   displayName: Publish artifact
          #   inputs:
          #     PathtoPublish: 'my-react-app/build'
          #     ArtifactName: 'build-output'